openapi: 3.2.0
info:
  title: Annotation Competence Calendar API
  version: 1.0.0.0
security:
- Bearer: []
tags:
- name: AnnotationCompetenceCalendar
paths:
  /annotation-competence-calendar:
    get:
      tags:
      - AnnotationCompetenceCalendar
      parameters:
      - name: QueryType
        in: query
        schema:
          $ref: '#/components/schemas/AnnotationCompetenceCalendarQueryType'
      - name: CompetencePeriod
        in: query
        schema:
          type: string
          format: date-time
      - name: ConsigneeId
        in: query
        schema:
          type: string
          format: uuid
      - name: AgencyId
        in: query
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnotationCompetenceCalendarResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: Get annotation competence calendar
      x-summary-source: derived
      operationId: getAnnotationCompetenceCalendar
      x-operation-id-source: derived
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        correlationId:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Errs'
      additionalProperties: false
    Errs:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
      additionalProperties: false
    AnnotationCompetenceCalendarQueryType:
      enum:
      - COMPETENCE_INFO
      - CALENDAR_DETAILS
      type: string
    AnnotationCompetenceCalendarResponse:
      type: object
      properties:
        consultedCompetencePeriod:
          type:
          - string
          - 'null'
        currentCompetencePeriod:
          type:
          - string
          - 'null'
        startCompetencePeriod:
          type:
          - string
          - 'null'
        endCompetencePeriod:
          type:
          - string
          - 'null'
        initNotificationInfoDate:
          type:
          - string
          - 'null'
        endNotificationInfoDate:
          type:
          - string
          - 'null'
        initLimitBookkeepingDate:
          type:
          - string
          - 'null'
        endLimitBookkeepingDate:
          type:
          - string
          - 'null'
        paymentTransferDocDate:
          type:
          - string
          - 'null'
        limitTransferDate:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      scheme: bearer
      bearerFormat: JWT
