openapi: 3.2.0
info:
  title: Outstanding Balance API
  version: 1.0.0.0
security:
- Bearer: []
tags:
- name: Outstanding Balance
paths:
  /outstanding-balance/inform:
    post:
      tags:
      - Outstanding Balance
      summary: Inform outstanding balance
      parameters:
      - name: correspAgentId
        in: header
        description: Bank Correspondent Agent Id
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceInformedRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceInformedRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceInformedRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutstandingBalanceInformedResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: postOutstandingBalanceInform
      x-operation-id-source: derived
  /outstanding-balance/reject:
    post:
      tags:
      - Outstanding Balance
      summary: Reject outstanding balance
      parameters:
      - name: correspAgentId
        in: header
        description: Bank Correspondent Agent Id
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceRejectedRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceRejectedRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OutstandingBalanceRejectedRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutstandingBalanceRejectedResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: postOutstandingBalanceReject
      x-operation-id-source: derived
  /outstanding-balance/settled-purchase/{outstandingBalancetInformedId}:
    post:
      tags:
      - Outstanding Balance
      summary: Settled purchase
      parameters:
      - name: outstandingBalancetInformedId
        in: path
        description: Id outstanding balance informed
        required: true
        schema:
          type: string
          format: uuid
      - name: correspAgentId
        in: header
        description: Bank Correspondent Agent Id
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettledPurchaseResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: postOutstandingBalanceSettledPurchaseByOutstandingBalancetInformedId
      x-operation-id-source: derived
  /outstanding-balance/report-payment/{outstandingBalancePaymentId}:
    post:
      tags:
      - Outstanding Balance
      summary: Report the payment for outstanding balance
      parameters:
      - name: correspAgentId
        in: header
        description: Bank Correspondent Agent Id
        schema:
          type: string
      - name: outstandingBalancePaymentId
        in: path
        description: Id from outstanding balance payment
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutstandingBalancePaymentResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      operationId: postOutstandingBalanceReportPaymentByOutstandingBalancePaymentId
      x-operation-id-source: derived
components:
  schemas:
    OutstandingBalanceRejectedResponse:
      type: object
      properties:
        outstandingBalanceInformedId:
          type: string
          format: uuid
        status:
          type:
          - string
          - 'null'
        updateAt:
          type: string
          format: date-time
      additionalProperties: false
    OutstandingBalanceInformedResponse:
      required:
      - status
      type: object
      properties:
        outstandingBalanceInformedId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        status:
          type:
          - string
          - 'null'
      additionalProperties: false
    OutstandingBalanceInformedRequest:
      required:
      - debtorBalanceAmount
      - requestOutstandingBalanceId
      type: object
      properties:
        requestOutstandingBalanceId:
          type: string
          format: uuid
        debtorBalanceAmount:
          type: number
          format: double
        nameBeneficiary:
          type:
          - string
          - 'null'
        documentBenficiary:
          type:
          - string
          - 'null'
        expirationDate:
          type:
          - string
          - 'null'
          format: date-time
        description:
          type:
          - string
          - 'null'
        detailOutstandingBalance:
          type:
          - string
          - 'null'
        proposalRefinancing:
          type:
          - string
          - 'null'
        infoAccount:
          $ref: '#/components/schemas/InfoAccount'
      additionalProperties: false
    SettledPurchaseResponse:
      type: object
      properties:
        outstandingBalanceInformedId:
          type: string
          format: uuid
        statusOutstandingBalanceInformed:
          type:
          - string
          - 'null'
        updateAt:
          type: string
          format: date-time
        annotationId:
          type: string
          format: uuid
        statusAnnotation:
          type:
          - string
          - 'null'
      additionalProperties: false
    InfoAccount:
      required:
      - bank
      - branch
      - number
      type: object
      properties:
        bank:
          type:
          - string
          - 'null'
        branch:
          type:
          - string
          - 'null'
        number:
          type:
          - string
          - 'null'
      additionalProperties: false
    Errs:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        correlationId:
          type:
          - string
          - 'null'
        status:
          type:
          - string
          - 'null'
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Errs'
      additionalProperties: false
    OutstandingBalanceRejectedRequest:
      required:
      - outstandingBalanceInformedId
      type: object
      properties:
        outstandingBalanceInformedId:
          type: string
          format: uuid
        description:
          type:
          - string
          - 'null'
      additionalProperties: false
    OutstandingBalancePaymentResponse:
      type: object
      properties:
        outstandingBalancePaymentId:
          type: string
          format: uuid
        code:
          type:
          - string
          - 'null'
        message:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      scheme: bearer
      bearerFormat: JWT
