openapi: 3.2.0
info:
  title: Consignee API
  version: 1.0.0.0
security:
- Bearer: []
tags:
- name: Consignee
paths:
  /consignee:
    post:
      tags:
      - Consignee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConsigneeRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateConsigneeRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateConsigneeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConsigneeResponse'
      summary: Create consignee
      x-summary-source: derived
      operationId: postConsignee
      x-operation-id-source: derived
    put:
      tags:
      - Consignee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateConsigneeRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateConsigneeRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateConsigneeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsigneeResponse'
      summary: Replace consignee
      x-summary-source: derived
      operationId: putConsignee
      x-operation-id-source: derived
    get:
      tags:
      - Consignee
      parameters:
      - name: consigneeId
        in: query
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsigneeResponse'
      summary: Get consignee
      x-summary-source: derived
      operationId: getConsignee
      x-operation-id-source: derived
    delete:
      tags:
      - Consignee
      parameters:
      - name: consigneeId
        in: query
        schema:
          type: string
          format: uuid
      - name: agencyId
        in: query
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteConsigneeResponse'
      summary: Delete consignee
      x-summary-source: derived
      operationId: deleteConsignee
      x-operation-id-source: derived
components:
  schemas:
    CreditProviderType:
      enum:
      - SIAPE
      - CT
      - FGTS
      - INSS
      - ECONSIG_ARMY
      - FACIL_PI
      type: string
    CreateConsigneeResponse:
      required:
      - status
      type: object
      properties:
        consigneeId:
          type: string
          format: uuid
        agencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/CreateAgenciesResponse'
        status:
          type:
          - string
          - 'null'
      additionalProperties: false
    AgenciesRequest:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
        user:
          type:
          - string
          - 'null'
        agencyType:
          $ref: '#/components/schemas/CreditProviderType'
        apiKey:
          type:
          - string
          - 'null'
        registrationName:
          type:
          - string
          - 'null'
        rubricConfigs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RubricConfigRequest'
      additionalProperties: false
    RubricConfigRequest:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        partnerCode:
          type:
          - string
          - 'null'
        serviceCode:
          type:
          - string
          - 'null'
        typeProduct:
          $ref: '#/components/schemas/TypeProduct'
      additionalProperties: false
    TypeProduct:
      enum:
      - LOAN
      - CARD_CREDIT
      - CARD_BENEFICIARY
      - MONTHLY_DESC
      - SYNDICAL_DESC
      - PORTABILITY
      type: string
    UpdateRubricConfigRequest:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        partnerCode:
          type:
          - string
          - 'null'
        serviceCode:
          type:
          - string
          - 'null'
        typeProduct:
          $ref: '#/components/schemas/TypeProduct'
        exclude:
          type: boolean
      additionalProperties: false
    CreateAgenciesResponse:
      type: object
      properties:
        agencyId:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
    ConsigneeResponse:
      type: object
      properties:
        consigneeId:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        certificateName:
          type:
          - string
          - 'null'
        uf:
          type:
          - string
          - 'null'
        client:
          $ref: '#/components/schemas/ClientResponse'
        agencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AgenciesResponse'
      additionalProperties: false
    RubricConfigResponse:
      type: object
      properties:
        code:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        partnerCode:
          type:
          - string
          - 'null'
        serviceCode:
          type:
          - string
          - 'null'
        typeProduct:
          $ref: '#/components/schemas/TypeProduct'
      additionalProperties: false
    ClientResponse:
      type: object
      properties:
        clientId:
          type:
          - string
          - 'null'
        localId:
          type:
          - string
          - 'null'
        userId:
          type:
          - string
          - 'null'
      additionalProperties: false
    AgenciesResponse:
      type: object
      properties:
        agencyId:
          type: string
          format: uuid
        code:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
        user:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        apiKey:
          type:
          - string
          - 'null'
        registrationName:
          type:
          - string
          - 'null'
        rubricConfigs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RubricConfigResponse'
        updateAt:
          type:
          - string
          - 'null'
          format: date-time
      additionalProperties: false
    UpdateAgenciesResquest:
      type: object
      properties:
        agencyId:
          type:
          - string
          - 'null'
          format: uuid
        code:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
        user:
          type:
          - string
          - 'null'
        agencyType:
          $ref: '#/components/schemas/CreditProviderType'
        apiKey:
          type:
          - string
          - 'null'
        registrationName:
          type:
          - string
          - 'null'
        rubricConfigs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/UpdateRubricConfigRequest'
      additionalProperties: false
    CreateConsigneeRequest:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        certificateName:
          type:
          - string
          - 'null'
        uf:
          type:
          - string
          - 'null'
        agencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AgenciesRequest'
      additionalProperties: false
    DeleteConsigneeResponse:
      type: object
      properties:
        consigneeId:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        certificateName:
          type:
          - string
          - 'null'
        uf:
          type:
          - string
          - 'null'
        client:
          $ref: '#/components/schemas/ClientResponse'
        agency:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/AgenciesResponse'
      additionalProperties: false
    UpdateConsigneeRequest:
      required:
      - consigneeId
      type: object
      properties:
        consigneeId:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        certificateName:
          type:
          - string
          - 'null'
        uf:
          type:
          - string
          - 'null'
        agencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/UpdateAgenciesResquest'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      scheme: bearer
      bearerFormat: JWT
